name: 🙌 Feature Request
about: 프로젝트에 대한 새로운 아이디어를 공유해주세요!
description: 프로젝트에 대한 새로운 아이디어를 공유해주세요!
title: "feat: "
assignees:
  - 6h15m
body:
  - type: textarea
    attributes:
      label:  💡 아이디어 설명
      description: |
        아이디어를 떠올리게 된 문제 상황과, 해결 방안에 대해 설명해주세요 :)

  - type: textarea
    attributes:
      label:  📄 참고 문서
      description: |
        참고한 문서와 링크를 첨부해주세요.

  - type: textarea
    attributes:
      label: 🎸 기타 사항